name: studyfi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  http_parser: ^4.1.2
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    

  
